dist: trusty
sudo: required

language: cpp

git:
  depth: false

branches:
  only:
  - staging
  - trying
  - master

install:
- sudo apt-get --yes --no-install-recommends install snapd
- sudo snap install lxd
- sudo snap install snapcraft --classic
- sudo /snap/bin/lxd waitready
- sudo /snap/bin/lxd init --auto
- sudo adduser $USER lxd

before_script:
- "[ ! -f tests/travis-${BUILD_TYPE}.patch ] || patch -p1 < tests/travis-${BUILD_TYPE}.patch"

jobs:
  include:
    - &release
      env: BUILD_TYPE=RelWithDebInfo
      script:
          #      - sg lxd -c 'env PATH=/snap/bin:$PATH SNAPCRAFT_CONTAINER_BUILDS=1 /snap/bin/snapcraft'
      - wget -O multipass_`git describe`_amd64.snap https://api.snapcraft.io/api/v1/snaps/download/mA11087v6dR3IEcQLgICQVjuvhUUBUKM_344.snap
      cache:
        directories:
        - snap
      before_cache:
      - mkdir -p snap
      - cp multipass_`git describe`_amd64.snap snap/

        #    - env: BUILD_TYPE=Debug
        #      script:
        #      - sg lxd -c 'env PATH=/snap/bin:$PATH SNAPCRAFT_CONTAINER_BUILDS=1 /snap/bin/snapcraft build multipass'
        #      - sg lxd -c '/snap/bin/lxc start snapcraft-multipass'
        #      - sg lxd -c
        #          '/snap/bin/lxc exec snapcraft-multipass --
        #             env CTEST_OUTPUT_ON_FAILURE=1
        #                 LD_LIBRARY_PATH=/root/build_multipass/stage/usr/lib/x86_64-linux-gnu/:/root/build_multipass/stage/lib/
        #                 /root/build_multipass/parts/multipass/build/bin/multipass_tests'
        #
        #    - env: BUILD_TYPE=Coverage
        #      script:
        #      - sg lxd -c 'env PATH=/snap/bin:$PATH SNAPCRAFT_CONTAINER_BUILDS=1 /snap/bin/snapcraft build multipass'
        #      - sg lxd -c '/snap/bin/lxc start snapcraft-multipass'
        #      - sg lxd -c
        #          '/snap/bin/lxc exec snapcraft-multipass --
        #             env CTEST_OUTPUT_ON_FAILURE=1
        #                 LD_LIBRARY_PATH=/root/build_multipass/stage/usr/lib/x86_64-linux-gnu/:/root/build_multipass/stage/lib/
        #                 cmake --build /root/build_multipass/parts/multipass/build --target covreport'
        #      after_success:
        #      - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

    - <<: *release
      stage: integration test
      script:
      - sudo snap install --dangerous --classic snap/multipass_`git describe`_amd64.snap
      before_cache:
      - rm snap/multipass_`git describe`_amd64.snap
