dist: xenial
sudo: required

language: cpp

git:
  depth: false

if: |
  branch IN (staging, trying, master)
  OR type = pull_request

addons:
  snaps:
  - &lxd lxd
  - &snapcraft
    name: snapcraft
    classic: true

env:
  global:
  - SNAPCRAFT_ENABLE_ERROR_REPORTING=0

install:
- sudo apt remove --purge --assume-yes lxd lxd-client
- sudo /snap/bin/lxd waitready
- sudo /snap/bin/lxd init --auto
- sudo adduser $USER lxd
- ccache --max-size=5G

before_script:
# patch build system for the build type being processed
- "[ ! -f tests/travis.patch ] || patch -p1 --no-backup-if-mismatch < tests/travis.patch"
- "[ ! -f tests/travis-${BUILD_TYPE}.patch ] || patch -p1 --no-backup-if-mismatch < tests/travis-${BUILD_TYPE}.patch"

# set up ccache
- sg lxd -c '/snap/bin/lxc profile set default environment.PATH "/usr/lib/ccache:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"'
- sg lxd -c '/snap/bin/lxc profile device add default ccache disk source=${HOME}/.ccache/ path=/root/.ccache'
- ccache --zero-stats

after_failure:
- cat /tmp/*/trace.txt

after_success:
- ccache --show-stats

cache: ccache

jobs:
  include:
    - &build
      env: BUILD_TYPE=Defaults
      script:
      - sg lxd -c '/snap/bin/snapcraft pull --use-lxd multipass'
      - sg lxd -c '/snap/bin/snapcraft build --use-lxd multipass'

    - <<: *build
      env: BUILD_TYPE=Clang

    - <<: *build
      env: BUILD_TYPE=Gold

    - <<: *build
      env: BUILD_TYPE=Lld

    - <<: *build
      env: BUILD_TYPE=ClangGold

    - <<: *build
      env: BUILD_TYPE=ClangLld
